### ISSUE TITLE
line height too low for multi-line text

### ISSUE THREAD

**Issue by shirl-wang** [pivotal-cf/pivotal-ui#574] opened 2018-10-23 18:28 UTC
Could this be increased to 18px? Currently the default value is at 16px, and it's too small for 12px type. Default line height for `type-xs` is 20px, we should make this the same for tooltips or at least, a little larger than 16px.

https://github.com/pivotal-cf/pivotal-ui/blob/3b68ccf101468851562d6d759824be92d5ac2b67/src/css/tooltips/tooltips.scss#L43

**Comment by mingxiao** [comment] 2018-10-26 19:17
<img width="1180" alt="screen shot 2018-10-26 at 12 15 39 pm" src="https://user-images.githubusercontent.com/1500022/47587799-efc66800-d918-11e8-961a-d92ccf577828.png">

We are unable to reproduce this issue. Seems like the tooltip is expanding according to its content. Could you elaborate on what you are seeing?

**Comment by kennyw12** [comment] 2019-10-09 19:32
@shirl-wang did you still want this change? If so, which versions of PUI should this affect?

**Comment by sweinstein22** [comment] 2020-05-01 16:57
I'm going to close this issue as there hasn't been any activity for a while. If this is still an issue that needs to be addressed feel free to reopen it.

**Closed by sweinstein22** 2020-05-01 16:57 UTC
