### ISSUE TITLE
UI.AlertNotification style regression (also, does not accept class names)

### ISSUE THREAD

**Issue by pmeskers** [pivotal-cf/pivotal-ui#158] opened 2015-06-04 14:19 UTC
The UI.AlertNotification used to create a bell icon with a size of font-size of h4. But now icons can only be sized via `fa-h{size}`, and the UI.AlertNotification does not do this, so it's much smaller than it used to be. This is a breaking change/regression for us.

Also, we can't add the class ourselves, because the component doesn't accept class names.

**Comment by gpleiss** [comment] 2015-06-04 16:26
https://www.pivotaltracker.com/story/show/96041150

**Comment by gpleiss** [comment] 2015-06-08 17:11
@pmeskers now that we've added the `fa-h{size}` classes, would you be able to address this regression yourselves and make a PR?

cc/ @stubbornella

**Comment by bebepeng** [comment] 2015-06-09 15:33
@gpleiss, @stubbornella  Would you like us to still hard code in the size through use of the new class or should the class be passed in? Personally, I think the bell is meant to be a certain size by design, but I could be swayed otherwise.

**Comment by stubbornella** [comment] 2015-06-10 00:25
Imo, you should make the bell a specific component that doesn't by default
require utils. E.g.

.dropdown-notifications{
Bell specific styles here
}

**Comment by gpleiss** [comment] 2015-06-10 14:49
Seconded. Maybe the fa-h2 size can be a default, but I think it should be
customizable.

**Comment by stubbornella** [comment] 2015-06-24 06:35
I'm going to close this issue since we unblocked you, I'll open a new issue for making the bell work without modifiers.

**Closed by stubbornella** 2015-06-24 06:35 UTC
