### ISSUE TITLE
CheckboxDropdown messes up modal component's CSS

### ISSUE THREAD

**Issue by thausler786** [pivotal-cf/pivotal-ui#573] opened 2018-10-22 21:31 UTC
## What version of Pivotal UI are you using?

17.0.2

## What browser and version are you using?

Chrome almost latest

## What behavior are you seeing?

When the CheckboxDropdown component is imported
And we are compiling our assets (not hotloading)
Then all modal 'X' close buttons are in the lower left corner of the modal for all app pages

## What do you expect to see?

The all modal 'X' close buttons are in the original spot (upper right corner) of the modal for all app pages.

**Comment by thausler786** [comment] 2018-10-22 21:32
![screen shot 2018-10-22 at 10 49 59 am](https://user-images.githubusercontent.com/1448254/47320778-41b07a80-d607-11e8-9703-76c3dbfc4b48.png)

**Comment by mingxiao** [comment] 2018-10-26 19:10
We cannot reproduce this. We are compiling our assets and disabled hot loading.

Can you provide a simple application that reproduces this issue?

**Comment by thausler786** [comment] 2018-10-26 23:41
We have made an app that reproduces the issue:

https://github.com/thausler786/pui-bug-app

Thanks,

Tim Hausler && Steven Locke

**Comment by thausler786** [comment] 2018-10-26 23:43
Another observation: although we do render the CheckboxDropdown component in our example app, that is not technically necessary, and we were able to reproduce the bug solely by importing the component.

**Comment by danjahner** [comment] 2018-12-18 19:01
Any updates on this item?

**Comment by reid47** [comment] 2018-12-18 19:21
@danjahner We're going to take a look today and try to fix in the near future!

**Comment by reid47** [comment] 2018-12-18 23:13
We've just released v17.1.2, which fixes this problem. Closing this issue now - feel free to reopen it or file another issue if you run into more problems.

**Closed by reid47** 2018-12-18 23:13 UTC

**Comment by danjahner** [comment] 2018-12-19 01:08
Deployed to prod. LGTM!
